name: Profile Header

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_ACCESS_TOKEN }}
          output_action: none

          # Options
          user: domai-tb
          template: classic
          extras_css: |
            .repository .name span:first-child,
            .activity .repo, .activity .issue, .activity .commit .sha {
              color: rgb(61, 133, 143);
            }

            .blue {
              color: rgb(61, 133, 143);
            }

            h1, h2, h3, .labels {
              color: rgba(255, 255, 255, 0.5);
            }
          base: header, activity, community, repositories
          base_indepth: yes
          config_display: large
          config_timezone: Europe/Berlin
          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: python, dart, c, rust, vue, go
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_forks: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_only: Stargazer, Explorer, Maintainer, Influencer, Developer, Polyglot
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
    
      - run: |
          set +e
          git fetch
          git checkout profile
          git pull
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          sudo mkdir -p ./assets/metrics/lowlighter
          sudo mv /metrics_renders/github-metrics.svg ./assets/metrics/lowlighter/header.svg
          git add --all
          git commit -m "Genrate Profile Header"
          git push
