name: GitHub-Profile-Metrics

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none

          # Options
          user: domai-tb
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_padding: 0,8 + 11%
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_only: Maintainer, Influencer, Developer, Polyglot
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 365
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 4
          repositories_forks: yes
    
      - run: |
          set +e
          git checkout actions
          git config user.name lowlighter-metrics[bot]
          git config user.email 41898282+lowlighter-metrics[bot]@users.noreply.github.com
          sudo mv /metrics_renders/* ./assets/metrics/
          git add --all
          git commit -m "Genrate Profile Metrics"
          git push
