name: GitHub Statistics

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_ACCESS_TOKEN }}
          output_action: none

          # Options
          user: domai-tb
          template: classic
          base: ""
          extras_css: |
            :root {
              --color-calendar-graph-day-L1-bg: rgba(61, 133, 143, 0.2);
              --color-calendar-graph-day-L2-bg: rgba(61, 133, 143, 0.5);
              --color-calendar-graph-day-L3-bg: rgba(61, 133, 143, 0.8);
              --color-calendar-graph-day-L4-bg: rgb(61, 133, 143);
            }

            h1, h2, h3, .labels {
              color: rgba(255, 255, 255, 0.8);
            }
          config_display: large
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 365
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage, byte-size
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_other: no
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          repositories_forks: yes
    
      - run: |
          set +e
          git fetch
          git checkout profile
          git pull
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          sudo mkdir -p ./assets/metrics/lowlighter
          sudo mv /metrics_renders/github-metrics.svg ./assets/metrics/lowlighter/statistics.svg
          git add --all
          git commit -m "Genrate Profile Metrics"
          git push
